version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'