version: '3.7'
services:
  redis-master:
    image: redis:6.0.10
    container_name: redis-master
    command: ["redis-server", "--appendonly", "yes", "--replica-announce-ip", "localhost", "--port", "6380"]
#    ports:
#      - "6380:6379"
    network_mode: host

  redis-replica:
    image: redis:6.0.10
    container_name: redis-replica
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "localhost", "6379", "--port", "6381"]
    depends_on:
      - redis-master
#    ports:
#      - "6381:6379"
    network_mode: host

  sentinel1:
    image: redis:5.0.7
    container_name: redis-sentinel1
    command: >
      sh -c "mkdir /etc/redis &&
             echo 'port 26379' > /etc/redis/sentinel.conf &&
             echo 'sentinel monitor mymaster localhost 6379 2' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26380' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26381' >> /etc/redis/sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf &&
             redis-sentinel /etc/redis/sentinel.conf"
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - "26379:26379"
    network_mode: host

  sentinel2:
    image: redis:5.0.7
    container_name: redis-sentinel2
    command: >
      sh -c "mkdir /etc/redis &&
             echo 'port 26380' > /etc/redis/sentinel.conf &&
             echo 'sentinel monitor mymaster localhost 6379 2' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26379' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26381' >> /etc/redis/sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf &&
             redis-sentinel /etc/redis/sentinel.conf"
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - "26380:26380"
    network_mode: host

  sentinel3:
    image: redis:5.0.7
    container_name: redis-sentinel3
    command: >
      sh -c "mkdir /etc/redis &&
             echo 'port 26381' > /etc/redis/sentinel.conf &&
             echo 'sentinel monitor mymaster localhost 6379 2' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26379' >> /etc/redis/sentinel.conf &&
             echo 'sentinel known-sentinel mymaster localhost 26380' >> /etc/redis/sentinel.conf &&
             echo 'sentinel down-after-milliseconds mymaster 5000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel failover-timeout mymaster 60000' >> /etc/redis/sentinel.conf &&
             echo 'sentinel parallel-syncs mymaster 1' >> /etc/redis/sentinel.conf &&
             redis-sentinel /etc/redis/sentinel.conf"
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - "26381:26381"
    network_mode: host

